### ISSUE TITLE
Extra deps

### ISSUE THREAD

**Issue by cystbear** [emedia-project/erlffmpeg#2]
What is the reason to add [dep_lager](https://github.com/emedia-project/erlffmpeg/blob/master/Makefile#L4) and [dep_edown](https://github.com/emedia-project/erlffmpeg/blob/master/Makefile#L7) as are deps?

I have tried use stripped rebar-based version without them, and my `ffmpeg:transcode("file.m4a", "file.mp3").` works fine.

**Comment by pampanelson** [comment]
I changed the Makefile under proj root path let make pass, 
DEPS = lager ucp jsx edown
dep_lager = git https://github.com/basho/lager.git master
dep_ucp = git https://github.com/glejeune/UnicodeCodePoints.git master
dep_jsx = git https://github.com/talentdeficit/jsx.git master
# dep_edown = git https://github.com/homeswap/edown.git master  // old one , removed
dep_edown = git https://github.com/uwiger/edown.git master    // new one, perhaps the 'original' edown

**Comment by glejeune** [comment]
Done ;)
